version: '3.8'

services:
  procloner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procloner-app
    restart: unless-stopped
    ports:
      - "${PORT:-3002}:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3002}
      - SESSION_SECRET=${SESSION_SECRET}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_CRAWL_MAX_REQUESTS=${RATE_LIMIT_CRAWL_MAX_REQUESTS:-10}
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-5}
      - DEFAULT_CRAWL_TIMEOUT=${DEFAULT_CRAWL_TIMEOUT:-120000}
      - SESSION_TIMEOUT_MS=${SESSION_TIMEOUT_MS:-300000}
      - DEFAULT_CRAWL_DEPTH=${DEFAULT_CRAWL_DEPTH:-3}
      - MAX_CRAWL_DEPTH=${MAX_CRAWL_DEPTH:-5}
      - PUPPETEER_HEADLESS=${PUPPETEER_HEADLESS:-true}
      - PUPPETEER_TIMEOUT=${PUPPETEER_TIMEOUT:-30000}
      - TEMP_DIR=/app/temp
      - MAX_TEMP_AGE_HOURS=${MAX_TEMP_AGE_HOURS:-24}
      - MAX_TEMP_SIZE_MB=${MAX_TEMP_SIZE_MB:-1024}
      - HSTS_MAX_AGE=${HSTS_MAX_AGE:-31536000}
      - CSP_REPORT_URI=/api/csp-report
    volumes:
      - temp_data:/app/temp
      - logs_data:/app/logs
    healthcheck:
      test: ["CMD", "node", "server/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - procloner-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: procloner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - procloner
    networks:
      - procloner-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

volumes:
  temp_data:
    driver: local
  logs_data:
    driver: local

networks:
  procloner-network:
    driver: bridge